// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Momentum.UI.Models;

public partial class Datas
{
    [Key]
    public int Id { get; set; }

    public DateOnly Data { get; set; }

    public bool Sabado { get; set; }

    public bool Domingo { get; set; }

    public bool Feriado { get; set; }

    public bool Ferias { get; set; }

    //[InverseProperty("DtFimNavigation")]
    //public virtual ICollection<Semestres> SemestresDtFimNavigation { get; set; } = new List<Semestres>();

    //[InverseProperty("DtIniNavigation")]
    //public virtual ICollection<Semestres> SemestresDtIniNavigation { get; set; } = new List<Semestres>();

    //[InverseProperty("DataInsertNavigation")]
    //public virtual ICollection<UCDocenteMomento> UCDocenteMomentoDataInsertNavigation { get; set; } = new List<UCDocenteMomento>();

    //[InverseProperty("DataMomento")]
    //public virtual ICollection<UCDocenteMomento> UCDocenteMomentoDataMomento { get; set; } = new List<UCDocenteMomento>();
}