// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Momentum.UI.Models;

public partial class Docentes
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Column(TypeName = "TEXT (300)")]
    public string Nome { get; set; } = string.Empty;

    [Required]
    [Column(TypeName = "TEXT (500)")]
    [EmailAddress(ErrorMessage = "Por favor insira um email válido")]
    public string Email { get; set; } = string.Empty;

    //[InverseProperty("Docente")]
    //public virtual ICollection<UCsDocente> UCsDocente { get; set; } = new List<UCsDocente>();
}