// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Momentum.UI.Models;

[Index("Nome", IsUnique = true)]
public partial class Momentos
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Column(TypeName = "TEXT (150)")]
    public string Nome { get; set; }

    [Column(TypeName = "NUMERIC (3)")]
    public int DiasUteisLancamentoAvaliacao { get; set; }

    [Column(TypeName = "NUMERIC (3)")]
    public int? DiasAvisoDataMomento { get; set; }

    [Column(TypeName = "NUMERIC (3)")]
    public int? DiasAvisoLancamentoAvaliacao { get; set; }

    //[InverseProperty("Momento")]
    //public virtual ICollection<UCDocenteMomento> UCDocenteMomento { get; set; } = new List<UCDocenteMomento>();
}