// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Momentum.UI.Models;

[Index("Nome", IsUnique = true)]
public partial class Regimes
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Nome { get; set; }

    //[InverseProperty("Regime")]
    //public virtual ICollection<UCDocenteMomento> UCDocenteMomento { get; set; } = new List<UCDocenteMomento>();
}