// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Momentum.UI.Models;

[Index("Descricao", IsUnique = true)]
public partial class Semestres
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Column(TypeName = "TEXT (100)")]
    public string Descricao { get; set; }

    public int DtIni { get; set; }

    public int DtFim { get; set; }

    //[ForeignKey("DtFim")]
    //[InverseProperty("SemestresDtFimNavigation")]
    //public virtual Datas DtFimNavigation { get; set; }

    //[ForeignKey("DtIni")]
    //[InverseProperty("SemestresDtIniNavigation")]
    //public virtual Datas DtIniNavigation { get; set; }

    //[InverseProperty("Semestre")]
    //public virtual ICollection<UCsDocente> UCsDocente { get; set; } = new List<UCsDocente>();
}