// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Momentum.UI.Models;

public partial class UCDocenteMomento
{
    [Key]
    public int Id { get; set; }

    public int UCsDocenteId { get; set; }

    public int MomentoId { get; set; }

    public int RegimeId { get; set; }

    public int DataMomentoId { get; set; }

    public double Peso { get; set; }

    public DateTime DataInsert { get; set; }

    //[InverseProperty("UCDocenteMomentoDataMomento")]
    [ForeignKey("DataMomentoId")]
    public virtual Datas DataMomento { get; set; }

    //[InverseProperty("UCDocenteMomento")]
    [ForeignKey("MomentoId")]
    public virtual Momentos Momento { get; set; }

    //[InverseProperty("UCDocenteMomento")]
    [ForeignKey("RegimeId")]
    public virtual Regimes Regime { get; set; }

    //[InverseProperty("UCDocenteMomento")]
    [ForeignKey("UCsDocenteId")]
    public virtual UCsDocente UCsDocente { get; set; }
}