// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Momentum.UI.Models;

public partial class UCDocenteMomento
{
    [Key]
    public int Id { get; set; }

    public int UCsDocenteId { get; set; }

    public int MomentoId { get; set; }

    public int RegimeId { get; set; }

    public int DataMomentoId { get; set; }

    public double Peso { get; set; }

    public int DataInsert { get; set; }

    //[ForeignKey("DataInsert")]
    //[InverseProperty("UCDocenteMomentoDataInsertNavigation")]
    //public virtual Datas DataInsertNavigation { get; set; }

    //[ForeignKey("DataMomentoId")]
    //[InverseProperty("UCDocenteMomentoDataMomento")]
    //public virtual Datas DataMomento { get; set; }

    //[ForeignKey("MomentoId")]
    //[InverseProperty("UCDocenteMomento")]
    //public virtual Momentos Momento { get; set; }

    //[ForeignKey("RegimeId")]
    //[InverseProperty("UCDocenteMomento")]
    //public virtual Regimes Regime { get; set; }

    //[ForeignKey("UCsDocenteId")]
    //[InverseProperty("UCDocenteMomento")]
    //public virtual UCsDocente UCsDocente { get; set; }
}