// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Momentum.UI.Models;

[Index("UnidadeCurricula", IsUnique = true)]
public partial class UCs
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Column(TypeName = "TEXT (500)")]
    public string UnidadeCurricula { get; set; }

    [Column(TypeName = "TEXT (50)")]
    public string InternalCod { get; set; }

    //[InverseProperty("UC")]
    //public virtual ICollection<UCsDocente> UCsDocente { get; set; } = new List<UCsDocente>();
}