// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Momentum.UI.Models;

public partial class UCsDocente
{
    [Key]
    public int Id { get; set; }

    public int DocenteId { get; set; }

    public int UCId { get; set; }

    public int SemestreId { get; set; }

    //[ForeignKey("DocenteId")]
    //[InverseProperty("UCsDocente")]
    //public virtual Docentes Docente { get; set; }

    //[ForeignKey("SemestreId")]
    //[InverseProperty("UCsDocente")]
    //public virtual Semestres Semestre { get; set; }

    //[ForeignKey("UCId")]
    //[InverseProperty("UCsDocente")]
    //public virtual UCs UC { get; set; }

    //[InverseProperty("UCsDocente")]
    //public virtual ICollection<UCDocenteMomento> UCDocenteMomento { get; set; } = new List<UCDocenteMomento>();
}